### ISSUE TITLE
Version control hygiene for Jupyter Notebooks

### ISSUE THREAD

**Issue by paulvautravers** [paulvautravers/satisfia-marl#12]
Jupyter notebooks and Git version control do not tend to mix well. Therefore, it's necessary that we implement some, or all, of the following to maintain best practices in regards to version control. 

- [ ] Use a git hook to always clear the output of Jupyter notebooks as they are pushed to the repo to ensure that we do not cuase conflicts simply because one of us left some output in the file
- [ ] Use nbdime as a 3rd party dependency (through pip) to cleanly manage jupyter notebooks in our rep

Not expected to need both of these

**Comment by atrudel** [comment]
Let's first see if nbdime is sufficient to handle merge conflicts.
If we don't need to clear the outputs when we commit the files, we will be able to see our experiments results directly on github.

**Comment by paulvautravers** [comment]
Seems that we can avoid any deeper work to manage different jupyter notebooks etc, so I will close this ticket.
